/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author runnan
 */
public enum CSGAppProp {
    
    
    //old
       // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    UPDATE_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    WRONG_TA_EMAIL_TITLE,
    WRONG_TA_EMAIL_MESSAGE,
    WRONG_STARTTIMEENDTIME_MESSAGE,
    WRONG_STARTTIMEENDTIME_TITLE,
    WRONG_ENDTIMESTARTTIME_TITLE,
    WRONG_ENDTIMESTARTTIME_MESSAGE,
    //new
        WORKSPACE_STATE_BUTTON_COURSE_PART_TEXT,
        WORKSPACE_STATE_BUTTON_TA_PART_TEXT,
        WORKSPACE_STATE_BUTTON_RECITATION_PART_TEXT,
        WORKSPACE_STATE_BUTTON_SCHEDULE_PART_TEXT,
        WORKSPACE_STATE_BUTTON_PROJECT_PART_TEXT,
    
        //TA part
//        TAS_HEADER_TEXT, 
        UNDERGRADE_COLUMN_TEXT,
//        NAME_COLUMN_TEXT, 
//        EMAIL_COLUMN_TEXT, 
//        NAME_PROMPT_TEXT, 
//        EMAIL_PROMPT_TEXT, 
//        ADD_BUTTON_TEXT, 
//        UPDATE_BUTTON_TEXT,
//        CLEAR_BUTTON_TEXT,
//        OFFICE_HOURS_SUBHEADER, 
        START_HOURS,
        END_HOURS,
        
        
        //course part
        //TOP PANE
        COURSE_WORKSPACE_PART_TOP_PANE_HEADER_TEXT, 
        COURSE_WORKSPACE_PART_TOP_PANE_SUBJECT_TEXT,
        COURSE_WORKSPACE_PART_TOP_PANE_NUMBER_TEXT,
        COURSE_WORKSPACE_PART_TOP_PANE_SEMESTER_TEXT, 
        COURSE_WORKSPACE_PART_TOP_PANE_TITLE_TEXT, 
        COURSE_WORKSPACE_PART_TOP_PANE_YEAR_TEXT, 
        COURSE_WORKSPACE_PART_TOP_PANE_INCTRUCTOR_NAME_TEXT, 
        COURSE_WORKSPACE_PART_TOP_PANE_INCTRUCTOR_HOME_TEXT, 
        COURSE_WORKSPACE_PART_TOP_PANE_EXPORT_DIR_TEXT,
        CHANGE_TEXT,
        //center pane
            COURSE_WORKSPACE_PART_CENTER_PANE_HEADER_TEXT,
        DESCRIPTION_DETAIL_TEXT,
        TEMPLATE_BUTTON_TEXT,
        SITE_PAGES_TEXT, 
        USE_COLIMN_TEXT, 
        NAVBAR_TITLE_COLUMN_TEXT,
        FILE_NAME_COLUMN_TEXT,
        SCRIPT_COLUMN_TEXT,
        //bottom pane
         
        BUTTOM_PANE_HEADER_LABEL_TEXT,
        BANNER_LABEL_TEXT, 
        STYLESHEET_LABEL_TEXT,
        LEFT_LABEL_TEXT,
        RIGHT_LABEL_TEXT,
        NOTE_DESCRIPTION_TEXT,
   
        
        
        //recitations part
        RECITATION_HEADER_TEXT, 
        SECTION_COLUMN_TEXT, 
        INSTRUCTOR_COLUMN_TEXT, 
        DAYTIME_COLUMN_TEXT, 
        LOCATION_COLUMN_TEXT, 
        TA_COLUMN_TEXT, 
        ADD_EDIT_TEXT, 
        SUPERVISING_TA_TEXT, 
        ADD_UPDATE_TEXT,
        //schedule part
        SCHEDULE_HEADER_TEXT, 
        CALENDAR_HEADER_TEXT, 
        STARTING_DATE_TEXT,
        ENDING_DATE_TEXT,
        SCHEDULE_ITEMS_TEXT, 
        TYPE_COLUMN_TEXT, 
        DATE_COLUMN_TEXT,
        TITLE_COLUMN_TEXT,
        TOPIC_COLUMN_TEXT,
        TIME_TEXT,
        LINK_TEXT,
        CRITERIA_TEXT,
        
        //project part
        PROJECTS_HEADER_TEXT, 
        TEAMS_TEXT,
        COLOR_COLUMN_TEXT, 
        TEXT_COLOR_COLUMN_TEXT,
        COLOR_TEXT, 
        TEXT_COLOR_TEXT,
        STUDENTS_TEXT,
        FIRST_NAME_COLUMN_TEXT,
        LAST_NAME_COLUMN_TEXT, 
        TEAM_TEXT, 
        ROLE_TEXT, 
        
        
        //ta part
//        OFFICE_HOURS_TABLE_HEADERS, 
//        DAYS_OF_WEEK, 
//        
//      //ta wrong message
//        MISSING_TA_NAME_TITLE,
//        MISSING_TA_NAME_MESSAGE,
//        MISSING_TA_EMAIL_TITLE,
//        MISSING_TA_EMAIL_MESSAGE,
//        TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
//        TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
//        WRONG_TA_EMAIL_TITLE,
//        WRONG_TA_EMAIL_MESSAGE, 
        
        
        START_OVER_END_TITLE,
        START_OVER_END_MESSAGE,
        OFFICE_HOURS_REMOVED_TITLE,
        OFFICE_HOURS_REMOVED_MESSAGE,
        
        
        
        
        //diago
        CHOOSE_EXPORT_DIR,
        CHOOSE_TEMPLE_DIR,
        WRONG_RECITATION_TITLE,
        WRONG_RECITATION_MESSAGE,
        WRONG_SCHEDULEITEM_TITLE,
        WRONG_SCHEDULEITEM_MESSAGE,
        WRONG_TEAM_TITLE,
        WRONG_TEAM_MESSAGE,
        WRONG_STUDENT_TITLE,
        WRONG_STUDENT_MESSAGE,
        WRONG_TITLE,
        
        PROVE_TEAM_NAME,
        PROVE_TEAM_LINK,
        PROVE_RECITATION_SECTION,
        PROVE_RECITATION_DAYTIME,
        PROVE_RECITATION_LOCATION,
        PROVE_STUDENT_NAME,
        PROVE_TYPE_MESSAGE,
        TEMPLE_HAVE_HTML
        
        
        
        
      
        
        
  
}
